FROM hypriot/rpi-node
#FROM resin/rpi-raspbian:wheezy
MAINTAINER Chris Guest <chris.guest@magentys.io>

#RUN apt-get update
#EXPOSE 3000

#RUN sudo apt-get install libfontconfig	
#RUN apt-get install libfontconfig1

#RUN apt-get -f install

#ENV LOCALGOVERSION=3.0.4
#ENV BINARY=grafana_$LOCALGOVERSION_armhf.deb
#RUN wget https://s3.eu-central-1.amazonaws.com/belodetech/$BINARY
#RUN sudo dpkg -i $BINARY

######
# USE THIS INSTEAD
# docker run -d -p 3000:3000 --name grafana2 fg2it/grafana-armhf:v3.1.1
######
